# Generated by Django 4.0.5 on 2022-06-30 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(help_text='A2K####', max_length=10, null=True)),
                ('cnic', models.CharField(max_length=20, null=True, verbose_name='CNIC')),
                ('primary_phone', models.CharField(max_length=20, null=True)),
                ('secondary_phone', models.CharField(blank=True, help_text='Optional', max_length=20, null=True)),
                ('image', models.ImageField(blank=True, default='users/dummy.jpg', null=True, upload_to='users/')),
                ('address', models.TextField(max_length=200, null=True)),
                ('dob', models.DateField(blank=True, help_text='From CNIC', null=True, verbose_name='Date of birth')),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('B+', 'B+'), ('O+', 'O+'), ('AB+', 'AB+'), ('A-', 'A-'), ('B-', 'B-'), ('O-', 'O-'), ('AB-', 'AB-')], help_text='Optional', max_length=5, null=True, verbose_name='Blood Group')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
